name: SurfaceScanner
version: 1.0
main: com.thinpixel.SurfaceScanner
api-version: 1.20
author: Gemini
description: High-resolution surface scanning for Thin-Pixel data.
commands:
  # No commands needed yet as we use the Diamond Hoe interface